# Generated by Django 4.2.8 on 2024-01-16 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voicephishing', '0003_alter_voicephishingrecord_diagnosis_result_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_type', models.CharField(choices=[('통화 녹음본으로 입력하기', '통화 녹음본으로 입력하기'), ('직접 통화 내용 입력하기', '직접 통화 내용 입력하기')], max_length=50)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='voice_recordings/')),
                ('call_details', models.TextField()),
                ('diagnosis_date', models.DateTimeField(auto_now_add=True)),
                ('suspicion_percentage', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='voicephishingrecord',
            name='report_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='voicephishingrecord',
            name='reporter',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
