# Generated by Django 4.2.8 on 2024-01-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicephishing', '0004_diagnosis_voicephishingrecord_report_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='call_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
