# Generated by Django 4.2.8 on 2024-01-16 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voicephishing', '0005_alter_diagnosis_call_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='audio_file',
        ),
    ]
