# Generated by Django 4.2.8 on 2024-01-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicephishing', '0006_remove_diagnosis_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='voice_recordings/'),
        ),
    ]
