# Generated by Django 4.2.8 on 2024-01-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_report_voice_phishing_record'),
        ('voicephishing', '0007_diagnosis_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='audio_file',
            field=models.FileField(upload_to='voice_recordings/'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='call_details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='suspicion_percentage',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='VoicePhishingRecord',
        ),
    ]
