# Generated by Django 4.2.8 on 2024-01-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicephishing', '0008_alter_diagnosis_audio_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='voice_recordings/'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='call_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='suspicion_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
