# Generated by Django 4.2.8 on 2024-01-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicephishing', '0010_alter_diagnosis_call_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='call_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
