# Generated by Django 4.2.8 on 2024-01-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('수사기관 사칭형', '수사기관 사칭형'), ('대출사기형', '대출사기형')], max_length=50),
        ),
    ]
