# Generated by Django 4.2.8 on 2024-01-15 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voicephishing', '0003_alter_voicephishingrecord_diagnosis_result_and_more'),
        ('community', '0002_report_report_number_alter_report_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='voice_phishing_record',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='voicephishing.voicephishingrecord'),
        ),
    ]
