# Generated by Django 4.2.8 on 2024-01-18 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voicephishing', '0007_diagnosis_audio_file'),
        ('community', '0003_alter_report_voice_phishing_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='voice_phishing_record',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='voicephishing.diagnosis'),
        ),
    ]
