# Generated by Django 4.2.8 on 2024-01-22 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0004_alter_report_voice_phishing_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='nickname',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='nickname_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
