# Generated by Django 4.2.8 on 2024-01-22 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_comment_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='nickname',
        ),
    ]
