# Generated by Django 4.2.8 on 2024-01-31 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_askcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ask',
            old_name='Ask_content',
            new_name='ask_content',
        ),
        migrations.RenameField(
            model_name='ask',
            old_name='Ask_title',
            new_name='ask_title',
        ),
    ]
