# Generated by Django 4.2.8 on 2024-01-31 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_rename_ask_content_ask_ask_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='askcomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='askcomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Ask',
        ),
        migrations.DeleteModel(
            name='AskComment',
        ),
    ]
