# Generated by Django 4.2.8 on 2024-01-31 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_ask_askcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ask',
            old_name='ask_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='ask',
            old_name='ask_title',
            new_name='title',
        ),
    ]
