# Generated by Django 4.2.8 on 2024-02-20 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_alter_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diagnosis',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
