# Generated by Django 4.2.8 on 2024-01-11 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customuser_options_alter_customuser_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='number',
        ),
    ]
