# Generated by Django 4.2.8 on 2024-01-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_customuser_nickname_remove_customuser_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='number',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
